###Get list of all users

GET http://localhost:3000/users

###Get a particular user

GET http://localhost:3000/users/1111

###Create a user

POST  http://localhost:3000/users
Content-Type: application/json

{
    "content":"Hi There"
}
